# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'self-hosted pool'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global yarn
  displayName: 'Install Yarn'

- script: |
    yarn install
    yarn build
  displayName: 'yarn install and build'

- task: Docker@2
